### ISSUE TITLE
Implement the value sets from the specification in the different forms

### ISSUE THREAD

**Issue by ManuelB** [ere-health/covid-19-green-certificate#13]
https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_dt-specifications_en.pdf

![Screenshot from 2021-06-05 18-24-05](https://user-images.githubusercontent.com/457641/120898458-3f21b880-c62b-11eb-9a76-fbecc3a100de.png)

**Comment by ManuelB** [comment]
Official documentation is here:
https://ec.europa.eu/health/ehealth/key_documents_en#anchor0

**Comment by ghost** [comment]
Are these values supposed to be added to the forms as a help for adding the values?

**Comment by richard-infai** [comment]
@ManuelB @tempuser5432 Is this table valid: https://www.pei.de/DE/arzneimittel/impfstoffe/covid-19/covid-19-node.html?

**Comment by ManuelB** [comment]
@richard-infai the table is valid. Feel free to use the data mentioned their.

**Comment by ManuelB** [comment]
Here are value sets from the EU: https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-value-sets_en.pdf
