### ISSUE TITLE
OpenApi-Spec for dgc

### ISSUE THREAD

**Issue by ghost** [ere-health/covid-19-green-certificate#15]

**Comment by ghost** [comment]
OpenApi-Spec for simple `GET`-params is available at https://github.com/ere-health/ere-ps-app/blob/feature/covid-19-green-digital-certificates/doc/dgc-openapi.yaml

**Comment by richard-infai** [comment]
Why would we not use the written names of the parameter in the source code from the the openapi.yaml?
E.g; `@QueryParam("fn") String familyName` It should make the code easier to read.
