### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by shinycovid** [ere-health/covid-19-green-certificate#16]
I have some problems to run this all, can`t find localhost :/

**Comment by ManuelB** [comment]
@shinycovid can you attach the log of the system?

**Comment by shinycovid** [comment]
It says error to unfile the jar…. the error data. :/

**Comment by ManuelB** [comment]
@shinycovid can you send a screenshot of the output? Normally the system should output around 200 lines of log data.

**Comment by shinycovid** [comment]
> @shinycovid can you send a screenshot of the output? Normally the system should output around 200 lines of log data.

![problem](https://user-images.githubusercontent.com/91400901/134966315-c36f073b-95e7-4f66-8403-00d5e24a2054.PNG)

**Comment by ManuelB** [comment]
@shinycovid there is a problem in you maven installation. Can you just rename the listed settings.xml so it won't be recognized by maven and try again?

**Comment by ManuelB** [comment]
@shinycovid the issue that you have is not relate to our software therefore I am closing it, feel free to reopen it.
