### ISSUE TITLE
Specify link interfaces for the AF_02 (the same AF_03) and AF_04

### ISSUE THREAD

**Issue by ManuelB** [ere-health/covid-19-green-certificate#9]
The solution should offer a simple interface that is based on passing GET parameters to the forms or directly to the certification url e.g:

http://localhost:8080/dgc/covid-19-certificate.html?fn=Blechschmidt&gn=Manuel ... (Shows prefilles form)
http://localhost:8080/api/certify/v2/issue?fn=Blechschmidt&gn=Manuel ... (Directly generates PDF)
...

4 URLs are necessary.

1. Prefill form for VaccinationCertificateRequest
2. Directly execute VaccinationCertificateRequest and deliver pdf
3. Prefill form for RecoveryCertificateRequest
4. Directly execute RecoveryCertificateRequest and deliver pdf

**Comment by ghost** [comment]
Since the values are only prefilled in the UI, I am going to use `#` instead of `?`.

**Comment by ManuelB** [comment]
The link looks like this:
http://localhost:8080/api/certify/v2/issue?fn=Manuel&gn=Blechschmidt&dob=1986-07-16&id=BSNR-ARZT&tg=840539006&vp=11193050005&mp=EU/1/20/1528&ma=ORG-100030215&dn=1&sd=1&dt=2021-07-13

**Comment by ManuelB** [comment]
Open API is here:
https://github.com/ere-health/dgc-ps-app/blob/main/doc/dgc-openapi-yaml
